import { Buffer } from "node:buffer";
import { readFile, writeFile } from "node:fs/promises";
import { execPath as processExecPath } from "node:process";

import { join } from "@visulima/path";
import { x } from "tinyexec";

import type { CompressionAlgorithm } from "./compress";
import { BYTECODE_ASSET_KEY } from "./compress";
import { createDebug } from "./debug";
import type { ResolvedExeTarget } from "./platform";
import { getHostArch, getHostPlatform } from "./target";

const debug = createDebug();

/**
 * The CommonJS module wrapper V8 compiles.
 *
 * The bundle is compiled as a plain script rather than a module because `vm.Script` is
 * the only API that accepts a code cache without an experimental flag, and it needs the
 * CommonJS free variables supplied explicitly.
 */
const WRAPPER_PREFIX = "(function (exports, require, module, __filename, __dirname) {";
const WRAPPER_SUFFIX = "\n});";

/**
 * V8 compiles function bodies lazily and keeps the source around to do it later. That is
 * fatal here: the shipped source is blank, so the first call into a cold function would
 * throw a syntax error. `--no-lazy` forces every function into the code cache up front,
 * and it must be set identically when producing and when consuming the cache, because
 * V8 mixes the active flags into the cache's validity hash.
 */
const EAGER_FLAG = "--no-lazy";

/** The synchronous `node:zlib` function the loader uses to undo each compression algorithm. */
const DECOMPRESSORS: Record<CompressionAlgorithm, string> = {
    brotli: "brotliDecompressSync",
    gzip: "gunzipSync",
    zstd: "zstdDecompressSync",
};

/** Wraps a CommonJS bundle so V8 sees a single function expression. */
const wrapSource = (source: string): string => `${WRAPPER_PREFIX}${source}${WRAPPER_SUFFIX}`;

/**
 * The script run inside the target Node.js binary to emit a code cache.
 *
 * It runs in a separate process because `--no-lazy` only takes effect when V8 starts
 * with it, and because the cache must be produced by the exact Node.js build that will
 * later consume it.
 */
const PRODUCER_SCRIPT = `const vm = require("node:vm");
const fs = require("node:fs");
const source = fs.readFileSync(process.argv[2], "utf8");
const script = new vm.Script(source, { produceCachedData: true });
const data = script.cachedData || script.createCachedData();

if (!data || data.length === 0) {
    throw new Error("V8 produced an empty code cache.");
}

fs.writeFileSync(process.argv[3], data);
`;

/**
 * The loader that replaces the bundle as the executable's main script.
 *
 * Everything it needs travels in the code cache and the embedded asset, so the bundle's
 * own source never reaches the executable.
 * @param sourceLength Length of the wrapped source, which V8 validates the cache against.
 * @param filename Path reported for the script when an error is thrown at runtime.
 * @param compression Algorithm the embedded cache was compressed with, if any.
 * @returns JavaScript that reconstructs and runs the cached script.
 */
const createLoaderSource = (sourceLength: number, filename: string, compression: CompressionAlgorithm | undefined): string => {
    const decompress = compression === undefined ? "raw" : `require("node:zlib").${DECOMPRESSORS[compression]}(raw)`;

    return `"use strict";
// Generated by packem — the application's code lives in the embedded V8 code cache.
const sea = require("node:sea");
const v8 = require("node:v8");
const vm = require("node:vm");

const raw = Buffer.from(sea.getRawAsset(${JSON.stringify(BYTECODE_ASSET_KEY)}));
const cachedData = ${decompress};

// Must match the flags the cache was produced with, or V8 rejects it.
v8.setFlagsFromString("${EAGER_FLAG}");

const script = new vm.Script(" ".repeat(${String(sourceLength)}), {
    cachedData,
    filename: ${JSON.stringify(filename)},
});

v8.setFlagsFromString("--lazy");

if (script.cachedDataRejected) {
    throw new Error(
        "This executable's embedded code cache was rejected by V8, so its code cannot be run. " +
            "A code cache is only valid for the exact Node.js build it was produced with; " +
            "rebuild the executable on this platform.",
    );
}

script.runInThisContext()(module.exports, require, module, __filename, __dirname);
`;
};

interface CompileBytecodeOptions {
    /** Algorithm used to shrink the embedded cache, if any. */
    compression: CompressionAlgorithm | undefined;
    /** Absolute path of the bundled CommonJS entry. */
    entryPath: string;
    /** Absolute path of the Node.js binary to compile with — the target's, not necessarily the host's. */
    nodePath: string;
    /** Scratch directory for the producer script and its output. */
    temporaryDirectory: string;
}

interface CompiledBytecode {
    /** Raw (still uncompressed) V8 code cache. */
    cachedData: Buffer;
    /** Byte length of the bundle the cache was produced from, for reporting. */
    sourceBytes: number;
    /** Length of the wrapped source in UTF-16 units, which the loader must reproduce exactly. */
    sourceLength: number;
}

/**
 * Compiles a bundled CommonJS entry into a V8 code cache.
 *
 * The cache is produced by spawning `nodePath` so that V8 starts with `--no-lazy` and so
 * that the cache is stamped with the target's own V8 version.
 * @param options The entry to compile, the Node.js binary to compile with, and a scratch directory.
 * @returns The code cache and the source length the loader has to reproduce.
 * @throws If the target binary cannot compile the bundle.
 */
const compileBytecode = async (options: CompileBytecodeOptions): Promise<CompiledBytecode> => {
    const { entryPath, nodePath, temporaryDirectory } = options;

    const source = await readFile(entryPath, "utf8");
    const wrapped = wrapSource(source);

    const wrappedPath = join(temporaryDirectory, "packem-bytecode-input.js");
    const producerPath = join(temporaryDirectory, "packem-bytecode-producer.cjs");
    const cachePath = join(temporaryDirectory, "packem-bytecode.bin");

    await Promise.all([writeFile(wrappedPath, wrapped), writeFile(producerPath, PRODUCER_SCRIPT)]);

    debug("Compiling bytecode with %s %s (source: %d chars)", nodePath, EAGER_FLAG, wrapped.length);

    // stderr is captured rather than inherited so a compile failure is reported as one
    // actionable error instead of a raw V8 stack trace interleaved with the build log.
    const result = await x(nodePath, [EAGER_FLAG, producerPath, wrappedPath, cachePath], {
        nodeOptions: { stdio: ["ignore", "ignore", "pipe"] },
    });

    if (result.exitCode !== 0) {
        throw new Error(
            `Failed to compile ${entryPath} to bytecode using ${nodePath}.\n${result.stderr.trim() || `The compiler exited with code ${String(result.exitCode)}.`}`,
        );
    }

    const cachedData = await readFile(cachePath);

    debug("Produced %d bytes of bytecode from %d bytes of source", cachedData.length, Buffer.byteLength(source));

    return { cachedData, sourceBytes: Buffer.byteLength(source), sourceLength: wrapped.length };
};

/**
 * Rejects target/entry combinations that cannot produce a working bytecode executable.
 *
 * A code cache is only valid for the exact Node.js build that produced it, and the only
 * way to produce one for a target is to run that target's binary — which the host can
 * only do for its own platform and architecture.
 * @param target The resolved target.
 * @param mainFormat The module format of the bundled entry.
 * @throws With an actionable message when bytecode cannot be produced for this target.
 */
const assertBytecodeSupported = (target: ResolvedExeTarget, mainFormat: "commonjs" | "module"): void => {
    if (mainFormat !== "commonjs") {
        throw new Error(
            "`exe.bytecode` only supports CommonJS output, because V8's code cache is exposed through `vm.Script`, which compiles classic scripts rather than ES modules.\n"
                + "Emit a CommonJS bundle for the executable entry (for example by setting `emitCJS: true` and pointing the entry at the `.cjs` output), or disable `exe.bytecode`.",
        );
    }

    if (target.platform !== getHostPlatform() || target.arch !== getHostArch()) {
        throw new Error(
            `\`exe.bytecode\` cannot build the ${target.platform}-${target.arch} target on a ${getHostPlatform()}-${getHostArch()} machine.\n`
                + "A V8 code cache has to be produced by running the target's own Node.js binary, which this machine cannot execute. "
                + "Build this target on a matching machine (a CI matrix job, for example), or disable `exe.bytecode`.",
        );
    }
};

/**
 * Picks the Node.js binary that must produce the code cache for a target.
 * @param target The resolved target.
 * @param downloadedNodePath The cached binary downloaded for a non-host target, if any.
 * @returns The absolute path of the binary to spawn.
 */
const getCompilerBinary = (target: ResolvedExeTarget, downloadedNodePath: string | undefined): string => downloadedNodePath ?? processExecPath;

export type { CompileBytecodeOptions, CompiledBytecode };
export { assertBytecodeSupported, compileBytecode, createLoaderSource, EAGER_FLAG, getCompilerBinary, wrapSource };
