packages:
    - "!**/__test__/**"
    - "!**/__tests__/**"
    - "!packages/packem/__fixtures__/css/**"
    - "!packages/packem/__fixtures__/package/**"
    - "!packages/packem/__fixtures__/url/**"
    - "packages/packem/__fixtures__/ecosystem/**"
    - "packages/**"
    - "examples/**"
    - "benchmarks/**"
