packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!packages/packem/__fixtures__/css/**'
  - '!packages/packem/__fixtures__/package/**'
  - '!packages/packem/__fixtures__/url/**'
  - packages/packem/__fixtures__/ecosystem/**
  - packages/**
  - examples/**

catalogs:
  build:
    '@rollup/plugin-alias': 5.1.1
    '@rollup/plugin-commonjs': 29.0.0
    '@rollup/plugin-dynamic-import-vars': 2.1.5
    '@rollup/plugin-inject': 5.0.5
    '@rollup/plugin-json': 6.1.0
    '@rollup/plugin-node-resolve': 16.0.1
    '@rollup/plugin-replace': 6.0.2
    '@rollup/plugin-wasm': 6.2.2
    '@rollup/pluginutils': 5.3.0
    esbuild: ^0.27.0
    rollup: ^4.53.2
    rollup-plugin-dts: 6.2.3
    rollup-plugin-license: 3.6.0
    rollup-plugin-lit-css: ^6.0.0
    rollup-plugin-polyfill-node: 0.13.0
    rollup-plugin-pure: ^0.4.0
    rollup-plugin-visualizer: 6.0.3
  cli:
    '@anolilab/multi-semantic-release': ^2.0.9
    '@anolilab/semantic-release-pnpm': 2.0.4
    '@anolilab/semantic-release-preset': ^11.0.5
    commitizen: ^4.3.1
    semantic-release: ^25.0.2
    taze: ^19.9.0
  dev:
    '@arethetypeswrong/cli': ^0.18.2
    '@babel/core': ^7.28.5
    '@babel/parser': 7.28.4
    '@mozilla/readability': ^0.6.0
    '@oxc-parser/binding-linux-x64-gnu': 0.91.0
    '@oxc-project/types': 0.91.0
    '@svgr/core': ^8.1.0
    '@swc/core': ^1.15.1
    '@swc/types': 0.1.25
    conventional-changelog-conventionalcommits: 9.1.0
    deeks: ^3.2.0
    detect-indent: ^7.0.2
    diff: ^8.0.2
    estree-walker: ^3.0.3
    hookable: 5.5.3
    lit: ^3.3.1
    mime: ^4.1.0
    oxc-parser: 0.91.0
    oxc-transform: ^0.97.0
    p-queue: ^9.0.0
    package-manager-detector: ^1.5.0
    picocolors: ^1.1.1
    rs-module-lexer: ^2.6.0
    sort-package-json: 3.4.0
    stylus: ^0.64.0
    sucrase: ^3.35.0
    sugarss: 5.0.1
    tempy: ^3.1.0
    tree-kill: ^1.2.2
    typedoc: 0.28.13
    typedoc-plugin-rename-defaults: 0.7.3
  frontend:
    '@vue/language-core': ^3.1.3
    react: ^19.2.0
    react-dom: ^19.2.0
    vue: ^3.5.24
  icons:
    lucide-static: ^0.553.0
  lint:
    '@anolilab/commitlint-config': ^6.0.6
    '@anolilab/eslint-config': ^16.4.2
    '@anolilab/lint-staged-config': ^3.0.37
    '@anolilab/prettier-config': ^6.0.7
    '@anolilab/textlint-config': ^9.0.8
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@rushstack/eslint-plugin-security': ^0.13.0
    '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
    eslint: ^9.36.0
    husky: ^9.1.7
    lint-staged: ^16.2.6
    prettier: ^3.6.2
    publint: ^0.3.15
    secretlint: ^11.2.5
    textlint: ^15.3.0
  markdown:
    turndown: ^7.2.2
    turndown-plugin-gfm: ^1.0.2
    typedoc-plugin-markdown: 4.9.0
  monorepo:
    nx: ^22.0.3
  network:
    browserslist: 4.26.2
    browserslist-config-anolilab: ^6.0.6
  node:
    '@antfu/install-pkg': 1.1.0
    '@clack/prompts': 0.11.0
    '@oxc-resolver/binding-linux-x64-gnu': 11.8.2
    cac: ^6.7.14
    cross-env: ^10.1.0
    dts-resolver: ^2.1.3
    execa: ^9.6.0
    glob-parent: 6.0.2
    oxc-resolver: 11.8.2
    pkg-pr-new: ^0.0.60
    rimraf: ^6.1.0
    tinyexec: 1.0.1
    tinyglobby: 0.2.15
  peer:
    package-manager-detector: ^1.5.0
  prod:
    '@arethetypeswrong/core': ^0.18.2
    '@babel/core': ^7.28.5
    '@babel/generator': ^7.28.5
    '@babel/parser': 7.28.4
    '@babel/types': ^7.28.5
    ast-kit: ^2.2.0
    audit-ci: ^7.1.0
    birpc: ^2.8.0
    cjs-module-lexer: ^2.1.1
    fastest-levenshtein: 1.0.16
    gpt-tokenizer: ^3.4.0
    happy-dom: ^20.0.10
    hookable: 5.5.3
    html-minifier-next: ^4.1.1
    is-ci: ^4.1.0
    micromatch: ^4.0.8
    mlly: 1.8.0
    oxc-parser: 0.93.0
    p-queue: ^9.0.0
    picomatch: 4.0.3
    plop: ^4.0.4
    preline: ^3.2.3
    rs-module-lexer: ^2.6.0
    sort-package-json: ^3.4.0
    source-map-js: ^1.2.1
  script:
    jiti: 2.6.0
    tsx: ^4.20.6
  style:
    '@csstools/css-parser-algorithms': 3.0.5
    '@csstools/css-tokenizer': 3.0.4
    '@csstools/postcss-slow-plugins': ^2.0.0
    '@tailwindcss/forms': ^0.5.10
    '@tailwindcss/node': ^4.1.17
    '@tailwindcss/oxide': ^4.1.17
    '@tailwindcss/typography': ^0.5.19
    clean-css: ^5.3.3
    cssnano: ^7.1.2
    icss-utils: ^5.1.0
    less: ^4.4.2
    lightningcss: ^1.30.2
    minireset.css: 0.0.7
    postcss: ^8.5.6
    postcss-custom-properties: 14.0.6
    postcss-load-config: ^6.0.1
    postcss-modules-extract-imports: ^3.1.0
    postcss-modules-local-by-default: ^4.2.0
    postcss-modules-scope: ^3.2.1
    postcss-modules-values: ^4.0.0
    postcss-value-parser: ^4.2.0
    sass: ^1.94.0
    sass-embedded: ^1.93.3
    tailwindcss: ^4.1.17
  test:
    '@sxzz/test-utils': ^0.5.12
    '@vitest/coverage-v8': ^4.0.8
    '@vitest/ui': ^4.0.8
    vitest: ^4.0.8
  tsc:
    '@total-typescript/ts-reset': ^0.6.1
    '@ts-macro/tsc': ^0.3.6
    '@volar/typescript': ^2.4.23
    typescript: ^5.9.3
    vue-tsc: ^3.1.3
  types:
    '@types/babel__generator': ^7.27.0
    '@types/bun': ^1.3.2
    '@types/clean-css': 4.2.11
    '@types/debug': ^4.1.12
    '@types/estree': ^1.0.8
    '@types/glob-parent': ^5.1.3
    '@types/html-minifier-next': 2.1.0
    '@types/icss-utils': ^5.1.2
    '@types/is-glob': ^4.0.4
    '@types/less': 3.0.8
    '@types/micromatch': ^4.0.10
    '@types/node': 24.5.2
    '@types/picomatch': ^4.0.2
    '@types/postcss-modules-local-by-default': ^4.0.2
    '@types/postcss-modules-scope': ^3.0.4
    '@types/react-dom': ^19.2.2
    '@types/semver': ^7.7.1
    '@types/stylus': ^0.48.43
    '@types/turndown': ^5.0.6
    '@types/uglifycss': ^0.0.11
    '@typescript/native-preview': 7.0.0-dev.20250922.1
  utils:
    cheerio: ^1.1.2
    defu: 6.1.4
    magic-string: 0.30.19
    semver: 7.7.2
  visulima:
    '@visulima/cerebro': 2.1.0
    '@visulima/colorize': 1.4.27
    '@visulima/css-style-inject': 1.0.0-alpha.9
    '@visulima/find-cache-dir': 2.0.4
    '@visulima/fs': 4.0.4
    '@visulima/humanizer': 2.0.3
    '@visulima/packem': 2.0.0-alpha.35
    '@visulima/packem-rollup': 1.0.0-alpha.27
    '@visulima/package': 4.1.4
    '@visulima/pail': 3.2.0
    '@visulima/path': 1.4.0
    '@visulima/rollup-plugin-css': 1.0.0-alpha.7
    '@visulima/source-map': 2.0.3
    '@visulima/tabular': ^3.1.1
    '@visulima/tsconfig': 2.1.0

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

ignoredOptionalDependencies:
  - fsevents
  - dtrace-provider

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - node-sass
  - nodehun
  - nx
  - oxc-resolver
  - rs-module-lexer
  - unrs-resolver

overrides:
  chrono-node@<2.2.4: '>=2.9.0'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.5'
  vite@>=7.1.0 <=7.1.10: '>=7.2.2'

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
