packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!packages/packem/__fixtures__/css/**'
  - '!packages/packem/__fixtures__/package/**'
  - '!packages/packem/__fixtures__/url/**'
  - packages/packem/__fixtures__/ecosystem/**
  - packages/**
  - examples/**

catalogs:
  build:
    '@rollup/plugin-alias': 6.0.0
    '@rollup/plugin-commonjs': 29.0.0
    '@rollup/plugin-dynamic-import-vars': 2.1.5
    '@rollup/plugin-inject': 5.0.5
    '@rollup/plugin-json': 6.1.0
    '@rollup/plugin-node-resolve': 16.0.3
    '@rollup/plugin-replace': 6.0.3
    '@rollup/plugin-wasm': 6.2.2
    '@rollup/pluginutils': 5.3.0
    '@visulima/packem-rollup': 1.0.0-alpha.37
    '@visulima/rollup-plugin-css': 1.0.0-alpha.17
    esbuild: 0.27.3
    rolldown: 1.0.0-rc.5
    rollup: 4.57.1
    rollup-plugin-dts: 6.3.0
    rollup-plugin-license: 3.7.0
    rollup-plugin-lit-css: ^6.0.0
    rollup-plugin-polyfill-node: 0.13.0
    rollup-plugin-pure: ^0.4.0
    rollup-plugin-svelte: ^7.2.3
    rollup-plugin-visualizer: 6.0.8
    unplugin-vue: 7.1.1
    vite: 7.3.1
  cli:
    '@anolilab/multi-semantic-release': 4.1.1
    '@anolilab/semantic-release-pnpm': 5.0.0
    '@anolilab/semantic-release-preset': 13.1.1
    commitizen: ^4.3.1
    semantic-release: 25.0.3
    taze: ^19.9.2
  database:
    babel-plugin-transform-hook-names: ^1.0.2
    oxc-transform: 0.114.0
  dev:
    '@arethetypeswrong/cli': ^0.18.2
    '@babel/core': 7.29.0
    '@babel/parser': 7.29.0
    '@mozilla/readability': ^0.6.0
    '@oxc-parser/binding-linux-x64-gnu': 0.114.0
    '@oxc-project/types': 0.114.0
    '@svgr/core': ^8.1.0
    '@swc/core': 1.15.11
    '@swc/helpers': ^0.5.18
    '@swc/types': 0.1.25
    babel-preset-solid: ^1.9.10
    conventional-changelog-conventionalcommits: 9.1.0
    deeks: ^3.2.0
    detect-indent: ^7.0.2
    diff: 8.0.3
    estree-walker: ^3.0.3
    hookable: 6.0.1
    lit: 3.3.2
    mime: ^4.1.0
    nodehun: ^3.0.2
    oxc-parser: 0.114.0
    oxc-transform: 0.114.0
    p-queue: 9.1.0
    package-manager-detector: ^1.6.0
    picocolors: ^1.1.1
    postgraphile: 4.14.1
    rs-module-lexer: ^2.6.0
    safe-stable-stringify: ^2.5.0
    sort-package-json: 3.6.1
    stylus: ^0.64.0
    sucrase: ^3.35.1
    sugarss: 5.0.1
    tempy: 3.2.0
    tree-kill: ^1.2.2
    typedoc: 0.28.17
    typedoc-plugin-rename-defaults: 0.7.3
  frontend:
    '@babel/preset-react': ^7.28.5
    '@radix-ui/react-tooltip': ^1.2.8
    '@vue/language-core': 3.2.4
    babel-plugin-react-compiler: 1.0.0
    preact: 10.28.4
    react: 19.2.4
    react-dom: 19.2.4
    svelte: 5.53.0
    vue: 3.5.28
  icons:
    lucide-static: 0.575.0
  lint:
    '@anolilab/commitlint-config': 9.0.0
    '@anolilab/eslint-config': 21.0.0
    '@anolilab/lint-staged-config': 5.1.0
    '@anolilab/prettier-config': 9.1.0
    '@anolilab/textlint-config': 12.1.0
    '@commitlint/cli': 20.4.2
    '@commitlint/config-conventional': 20.4.2
    '@secretlint/secretlint-rule-preset-recommend': 11.3.1
    eslint: 9.39.2
    husky: ^9.1.7
    lint-staged: ^16.2.7
    prettier: 3.8.1
    publint: 0.3.17
    secretlint: 11.3.1
    textlint: 15.5.1
  markdown:
    turndown: ^7.2.2
    turndown-plugin-gfm: ^1.0.2
    typedoc-plugin-markdown: 4.10.0
  monorepo:
    nx: 22.5.1
  network:
    browserslist: 4.28.1
    browserslist-config-anolilab: 8.0.0
  node:
    '@antfu/install-pkg': 1.1.0
    '@babel/preset-env': 7.29.0
    '@clack/prompts': 1.0.1
    cac: ^6.7.14
    cross-env: ^10.1.0
    dts-resolver: ^2.1.3
    execa: ^9.6.1
    glob-parent: 6.0.2
    oxc-resolver: 11.17.1
    pkg-pr-new: 0.0.63
    rimraf: 6.1.3
    tinyexec: 1.0.2
    tinyglobby: 0.2.15
  peer:
    package-manager-detector: ^1.6.0
  prod:
    '@arethetypeswrong/core': ^0.18.2
    '@babel/generator': 7.29.1
    '@babel/helper-validator-identifier': 7.28.5
    '@babel/parser': 7.29.0
    '@babel/types': 7.29.0
    '@visulima/packem-share': 1.0.0-alpha.18
    ast-kit: ^2.2.0
    audit-ci: ^7.1.0
    birpc: ^4.0.0
    cjs-module-lexer: 2.2.0
    clsx: ^2.1.1
    fastest-levenshtein: 1.0.16
    get-tsconfig: 4.10.1
    gpt-tokenizer: ^3.4.0
    happy-dom: 20.6.3
    hookable: 6.0.1
    html-minifier-next: 5.1.1
    is-ci: ^4.1.0
    micromatch: ^4.0.8
    mlly: 1.8.0
    obug: 2.1.1
    oxc-parser: 0.114.0
    p-queue: 9.1.0
    picomatch: 4.0.3
    plop: 4.0.5
    preline: 4.0.1
    rs-module-lexer: ^2.6.0
    safe-stable-stringify: ^2.5.0
    solid-js: 1.9.11
    sort-package-json: 3.6.1
    source-map-js: ^1.2.1
    tailwind-merge: 3.5.0
  script:
    jiti: 2.6.1
    tsx: ^4.21.0
  style:
    '@csstools/css-parser-algorithms': 4.0.0
    '@csstools/css-tokenizer': 4.0.0
    '@csstools/postcss-slow-plugins': 3.0.0
    '@tailwindcss/forms': 0.5.11
    '@tailwindcss/node': 4.2.0
    '@tailwindcss/oxide': 4.2.0
    '@tailwindcss/postcss': 4.2.0
    '@tailwindcss/typography': ^0.5.19
    '@visulima/css-style-inject': 1.0.0-alpha.14
    clean-css: ^5.3.3
    cssnano: 7.1.2
    icss-utils: ^5.1.0
    less: ^4.5.1
    lightningcss: 1.31.1
    minireset.css: 0.0.7
    postcss: ^8.5.6
    postcss-custom-properties: 15.0.0
    postcss-load-config: ^6.0.1
    postcss-modules: 6.0.1
    postcss-modules-extract-imports: ^3.1.0
    postcss-modules-local-by-default: ^4.2.0
    postcss-modules-scope: ^3.2.1
    postcss-modules-values: ^4.0.0
    postcss-value-parser: ^4.2.0
    sass: 1.97.3
    sass-embedded: 1.97.3
    tailwindcss: 4.2.0
  test:
    '@jridgewell/source-map': ^0.3.11
    '@sxzz/test-utils': 0.5.15
    '@vitest/coverage-v8': 4.0.18
    '@vitest/ui': 4.0.18
    vitest: 4.0.18
  tsc:
    '@babel/preset-typescript': ^7.28.5
    '@total-typescript/ts-reset': ^0.6.1
    '@ts-macro/tsc': 0.3.7
    '@volar/typescript': 2.4.28
    typescript: ^5.9.3
    vue-tsc: 3.2.4
  types:
    '@types/babel__core': ^7.20.5
    '@types/babel__generator': ^7.27.0
    '@types/bun': 1.3.9
    '@types/clean-css': 4.2.11
    '@types/debug': ^4.1.12
    '@types/estree': ^1.0.8
    '@types/glob-parent': ^5.1.3
    '@types/html-minifier-next': 4.1.0
    '@types/icss-utils': ^5.1.2
    '@types/is-glob': ^4.0.4
    '@types/less': 3.0.8
    '@types/micromatch': ^4.0.10
    '@types/node': 25.3.0
    '@types/picomatch': ^4.0.2
    '@types/postcss-modules-local-by-default': ^4.0.2
    '@types/postcss-modules-scope': ^3.0.4
    '@types/react': 19.2.14
    '@types/react-dom': ^19.2.3
    '@types/semver': ^7.7.1
    '@types/stylus': ^0.48.43
    '@types/turndown': ^5.0.6
    '@types/uglifycss': ^0.0.11
    '@typescript/native-preview': 7.0.0-dev.20250922.1
  utils:
    cheerio: 1.2.0
    defu: 6.1.4
    magic-string: 0.30.21
    semver: 7.7.4
  visulima:
    '@visulima/cerebro': 2.1.5
    '@visulima/colorize': 1.4.29
    '@visulima/find-cache-dir': 2.0.7
    '@visulima/fs': 4.1.0
    '@visulima/humanizer': 2.0.5
    '@visulima/package': 4.1.7
    '@visulima/packem': 2.0.0-alpha.40
    '@visulima/pail': 3.2.2
    '@visulima/path': 2.0.5
    '@visulima/source-map': 2.0.5
    '@visulima/tabular': ^3.1.3
    '@visulima/tsconfig': 2.1.3

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

ignoredOptionalDependencies:
  - fsevents
  - dtrace-provider

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - less
  - node-sass
  - nodehun
  - nx
  - oxc-resolver
  - rs-module-lexer
  - unrs-resolver

overrides:
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  chrono-node@<2.2.4: '>=2.9.0'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  glob@>=10.2.0 <10.5.0: '>=13.0.0'
  glob@>=11.0.0 <11.1.0: '>=13.0.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
  minimatch@<10.2.1: '>=10.2.1'
  oxc-parser: 0.99.0
  oxc-resolver: 11.14.0
  oxc-transform: 0.99.0
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.5'
  undici@<6.23.0: '>=6.23.0'
  vite@>=7.1.0 <=7.1.10: '>=7.3.0'

patchedDependencies:
  oxc-parser: patches/oxc-parser.patch

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
