/* eslint-disable no-secrets/no-secrets */
import type { Loader } from "esbuild";

/**
 * Valid file extensions for package.json exports field.
 * These extensions are considered valid for export paths in package.json.
 * @remarks
 * Includes all supported module formats and declaration files:
 * - JavaScript modules (.js, .mjs, .cjs)
 * - TypeScript modules (.ts, .mts, .cts)
 * - TypeScript declarations (.d.ts, .d.mts, .d.cts)
 * - JSX/TSX files (.jsx, .tsx) - React components
 * - JSON modules (.json)
 * - Native Node.js modules (.node) - compiled C++ addons
 * @see https://nodejs.org/api/packages.html#exports
 */
export const VALID_EXPORT_EXTENSIONS: ReadonlyArray<string> = [
    ".js",
    ".mjs",
    ".cjs", // JavaScript modules
    ".ts",
    ".mts",
    ".cts", // TypeScript modules
    ".d.ts",
    ".d.mts",
    ".d.cts", // TypeScript declarations
    ".jsx",
    ".tsx", // JSX/TSX files
    ".json", // JSON modules
    ".node", // Native Node.js modules (compiled C++ addons)
] as const;

/**
 * Default file extensions that Packem will process.
 * Includes JavaScript (ES modules and CommonJS), TypeScript, and their respective JSX/TSX variants.
 * @remarks
 * These extensions are used to determine which files should be processed by the bundler.
 * The order of extensions matters for resolution priority.
 * @example
 * ```ts
 * // Will match files like:
 * // - index.mjs
 * // - component.tsx
 * // - utils.cts
 * ```
 */
export const DEFAULT_EXTENSIONS: string[] = [
    ...VALID_EXPORT_EXTENSIONS, // Base extensions for all module types
    ".ctsx",
    ".mtsx", // Additional JSX/TSX variants (not standard for exports but processable)
];

/**
 * Default esbuild loaders configuration for different file extensions.
 * Maps file extensions to their corresponding esbuild loader type.
 * @remarks
 * - 'file' loader is used for static assets that should be emitted as-is
 * - 'js', 'jsx', 'ts', 'tsx' loaders are used for their respective file types
 * @example
 * ```ts
 * // Usage:
 * const loader = DEFAULT_LOADERS[".tsx"]; // Returns "tsx"
 * ```
 */
export const DEFAULT_LOADERS: Record<string, Loader> = {
    ".aac": "file",
    ".cjs": "js",
    ".cts": "ts",
    ".ctsx": "tsx",
    ".eot": "file",
    ".flac": "file",
    ".js": "js",
    ".jsx": "jsx",
    ".mjs": "js",
    ".mp3": "file",
    ".mp4": "file",
    ".mts": "ts",
    ".mtsx": "tsx",
    ".ogg": "file",
    ".otf": "file",
    ".ts": "ts",
    ".tsx": "tsx",
    ".ttf": "file",
    ".wav": "file",
    ".webm": "file",
    ".woff": "file",
    ".woff2": "file",
};

/**
 * Constant representing the production environment.
 * Used for environment-specific optimizations and configurations.
 * @constant
 */
export const PRODUCTION_ENV: string = "production";

/**
 * Constant representing the development environment.
 * Used for environment-specific features like source maps and debug information.
 * @constant
 */
export const DEVELOPMENT_ENV: string = "development";

/**
 * Set of runtime export conventions for special handling.
 * These conventions determine how exports are processed for different runtime targets.
 * @remarks
 * Currently supports:
 * - react-server: For React Server Components
 * - react-native: For React Native platform
 * - edge-light: For Edge runtime environments
 */
export const RUNTIME_EXPORT_CONVENTIONS: Set<string> = new Set<string>(["edge-light", "react-native", "react-server"]);

/**
 * Combined set of all special export conventions including runtime and environment-specific ones.
 * @remarks
 * Includes both runtime conventions and environment types (production/development).
 * Used for determining special processing rules during bundling.
 */
export const SPECIAL_EXPORT_CONVENTIONS: Set<string> = new Set<string>([DEVELOPMENT_ENV, PRODUCTION_ENV, ...RUNTIME_EXPORT_CONVENTIONS]);

/**
 * Regular expression to exclude node_modules from certain processing steps.
 * @remarks
 * Used to skip processing of node_modules files when not necessary,
 * improving build performance.
 */
export const EXCLUDE_REGEXP: RegExp = /node_modules/;

/**
 * Regular expression to match file extensions, including TypeScript declaration files.
 * @remarks
 * Used for file extension detection and manipulation.
 * Matches:
 * - TypeScript declaration files (.d.ts, .d.mts, .d.cts)
 * - Any file extension starting with a dot
 */
export const ENDING_REGEX: RegExp = /(?:\.d\.[mc]?tsx?|\.\w+)$/;

/**
 * Directory name for storing chunk files generated by Packem.
 * @remarks
 * This directory contains dynamically generated chunk files for code splitting.
 */
export const CHUNKS_PACKEM_FOLDER: string = "packem_chunks";

/**
 * Directory name for storing shared resources.
 * @remarks
 * This directory contains shared resources that are used across multiple chunks
 * or entry points.
 */
export const SHARED_PACKEM_FOLDER: string = "packem_shared";

/**
 * Regular expression to match file extensions that can be transformed.
 * @remarks
 * Matches JavaScript and TypeScript files, including their module variants:
 * - .js, .mjs, .cjs
 * - .ts, .mts, .cts
 * - .jsx, .tsx (and their module variants)
 * @example
 * ```ts
 * const canTransform = ALLOWED_TRANSFORM_EXTENSIONS_REGEX.test("file.ts"); // true
 * const canTransform = ALLOWED_TRANSFORM_EXTENSIONS_REGEX.test("file.css"); // false
 * ```
 */
// eslint-disable-next-line sonarjs/single-character-alternation
export const ALLOWED_TRANSFORM_EXTENSIONS_REGEX: RegExp = /\.(?:m|c)?(?:j|t)sx?$/;
