import { writeFile } from "node:fs/promises";

import { installPackage } from "@antfu/install-pkg";
import { cancel, intro, isCancel, log, outro, select, spinner } from "@clack/prompts";
import { cyan } from "@visulima/colorize";
import { join } from "@visulima/path";

import { hasPackemConfig } from "../config/utils/find-packem-file";
import type { BundlerName } from "./build";
import { buildInstallHint, TRANSFORMER_PACKAGE, type TransformerName } from "./installer";

const generatePackemConfig = (bundler: BundlerName, transformer: TransformerName): string =>
    `// Generated by \`packem\` first-run setup. See https://packem.dev for full options.
import { defineConfig } from "@visulima/packem/config";
import transformer from "@visulima/packem/transformer/${transformer}";

export default defineConfig({
    bundler: "${bundler}",
    declaration: true,
    transformer,
});
`;

const promptBundler = async (): Promise<BundlerName> => {
    const value = await select<BundlerName>({
        initialValue: "rollup",
        message: "Which bundler do you want to use?",
        options: [
            { hint: "stable, full feature set, supports DTS", label: "rollup", value: "rollup" },
            { hint: "experimental, fast — falls back to rollup for DTS", label: "rolldown", value: "rolldown" },
        ],
    });

    if (isCancel(value)) {
        cancel("Setup cancelled.");
        throw new Error("Packem setup was cancelled.");
    }

    return value;
};

const promptTransformer = async (): Promise<TransformerName> => {
    const value = await select<TransformerName>({
        initialValue: "esbuild",
        message: "Which transformer do you want to use?",
        options: [
            { hint: "fast, widely used", label: "esbuild", value: "esbuild" },
            { hint: "fastest, Rust-based", label: "oxc", value: "oxc" },
            { hint: "TypeScript-aware, Rust-based", label: "swc", value: "swc" },
            { hint: "minimal, JS-based", label: "sucrase", value: "sucrase" },
        ],
    });

    if (isCancel(value)) {
        cancel("Setup cancelled.");
        throw new Error("Packem setup was cancelled.");
    }

    return value;
};

const installPackagesWithSpinner = async (packages: string[], rootDirectory: string): Promise<void> => {
    if (packages.length === 0) {
        return;
    }

    const s = spinner();

    s.start(`Installing ${packages.join(", ")}`);

    try {
        await installPackage(packages, { cwd: rootDirectory, dev: true, silent: true });

        s.stop(`Installed ${packages.join(", ")}`);
    } catch (error) {
        s.stop(`Failed to install ${packages.join(", ")}`);

        throw error;
    }
};

/**
 * Runs only when packem.config is absent. Prompts for a bundler + transformer,
 * installs the chosen packages, and writes a minimal packem.config.ts. In CI
 * or non-TTY environments the function throws with an actionable, package-
 * manager-aware install hint instead of prompting.
 *
 * Dependency checks for the bundler/transformer named in an *existing* config
 * live in ensure-installed.ts so this function only handles the cold-start case.
 */
export const runFirstRunWizard = async (rootDirectory: string): Promise<void> => {
    if (await hasPackemConfig(rootDirectory)) {
        return;
    }

    const isInteractive = Boolean(process.stdout.isTTY) && !process.env.CI;

    if (!isInteractive) {
        const hint = await buildInstallHint(["rollup", "esbuild"], rootDirectory);

        throw new Error(
            `No packem.config found. Run packem in an interactive terminal to generate one, or install the defaults manually:\n  ${hint}\nand create a packem.config.ts.`,
        );
    }

    intro(cyan("Packem first-run setup"));
    log.info("No packem.config found — let's create one.");

    const bundler = await promptBundler();
    const transformer = await promptTransformer();

    // Rollup is required for DTS regardless of bundler choice, since
    // @visulima/rollup-plugin-dts isn't rolldown-compatible yet.
    const toInstall: string[] = [bundler];

    if (bundler === "rolldown") {
        toInstall.push("rollup");
    }

    toInstall.push(TRANSFORMER_PACKAGE[transformer]);

    await installPackagesWithSpinner(toInstall, rootDirectory);

    const configPath = join(rootDirectory, "packem.config.ts");

    await writeFile(configPath, generatePackemConfig(bundler, transformer), "utf8");

    log.success(`Created ${configPath}`);
    outro("Setup complete — continuing with build.");
};
