/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by packem
 * @see https://npmjs.com/@visulima/packem
 */
declare const css: string;
declare const test: "index_test_bcd2d774";
declare const container: "index_container_bcd2d774";

interface ModulesExports {
    test: string;
    container: string;
}

declare const modules_c21c94f2: ModulesExports;

export default modules_c21c94f2;

export { css, test, container };
