name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@d11bc32c7774bbdc35e4f89af140bc49ce4f9f68" # v15.1.1
        with:
            target-repo: "visulima/packem"
            onboarding-lead: "prisis"
