name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@94b27723e80256ce9bcace59884a051aca8fef22" # v18.0.1
        with:
            target-repo: "visulima/packem"
            onboarding-lead: "prisis"
