name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@586b057a4dfe3733a4b434f36f4de5f69c2e0bbd" # main
        with:
            target-repo: "visulima/packem"
            onboarding-lead: "prisis"
