name: "Lint"
on: # yamllint disable-line rule:truthy
    pull_request:
        branches: ["main", "alpha"]
permissions: {}
jobs:
    lint:
        permissions:
            contents: "read"
            pull-requests: "read"
        uses: "anolilab/workflows/.github/workflows/lint.yml@045a2d464dad0661a570c8a3c19f4b32bf9efad9" # v15.3.0+
        with:
            lint_eslint: true
            lint_types: true
            lint_attw: true
            lint_package_json: true
            lint_markdown: true
            lint_yaml: true
            lint_actionlint: true
            lint_rust: false
            node_version: "22"
