name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@586b057a4dfe3733a4b434f36f4de5f69c2e0bbd" # main
        with:
            target-repo: "visulima/packem"
