name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@d11bc32c7774bbdc35e4f89af140bc49ce4f9f68" # v15.1.1
        with:
            target-repo: "visulima/packem"
