name: "Semantic Pull Request"

on: # yamllint disable-line rule:truthy
    pull_request_target:
        types:
            - "opened"
            - "reopened"
            - "edited"
            - "synchronize"
    merge_group: # yamllint disable-line rule:empty-values

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/semantic-pull-request.yml@802f3b1d00b0ab47c3102b4f4ebd866b9f7f8fcf" # v18.0.3
        with:
            target-repo: "visulima/packem"
