name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@586b057a4dfe3733a4b434f36f4de5f69c2e0bbd" # main
        with:
            target-repo: "visulima/packem"
