name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@ea8d9012e452bfa5a85447527ba0db24698cafac" # v20.2.7
        with:
            target-repo: "visulima/packem"
