name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@d11bc32c7774bbdc35e4f89af140bc49ce4f9f68" # v15.1.1
        with:
            target-repo: "visulima/packem"
